name: miraca
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - pip
  - pip:
    - -e .  # install local cba package from src/cba
  - shapely>=2.0
  - geopandas
  - jupyter
  - rasterio
  - xarray
  - pytest
  - black
  - ruff
